# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed8f61f0928bca6b2fe8975644fc064d7a85b4c0a4c71e627900a0339f3462b791ba033c24e899d0ad40051e3f48fbb290e046c92f633a4d117ffa16c2190ad

test:
  secret_key_base: 5d810bc488c252a73a887d7492635ab7c66d9abca308460445624faa04787882086f334f9ec727f44ff55f8e74375ae73ca2ca23e7f1a5e7f3cd7b2f3ce36af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
